openapi: 3.2.0
info:
  title: AppyWay Platform Countries API
  version: '1.0'
  description: AppyWay Platform API allows developers to access a wide range of data related to parking, traffic, and mobility.
servers:
- url: https://api.appyway.com/v1/reference
security:
- apiKey: []
- oAuth2: []
tags:
- name: Countries
paths:
  /changeCountrySpecialDays:
    post:
      tags:
      - Countries
      summary: AppyWay Change Country Special Days
      description: Change Country Special Days
      operationId: post-changecountryspecialdays
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeCountrySpecialDaysCommand'
            example:
              specialDays:
              - id: string
                name: string
                isHoliday: true
                dates:
                - '2020-01-20'
              id: string
          text/json:
            schema:
              $ref: '#/components/schemas/ChangeCountrySpecialDaysCommand'
            example:
              specialDays:
              - id: string
                name: string
                isHoliday: true
                dates:
                - '2020-01-20'
              id: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/ChangeCountrySpecialDaysCommand'
            example:
              specialDays:
              - id: string
                name: string
                isHoliday: true
                dates:
                - '2020-01-20'
              id: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringOkResponse'
              example:
                success: true
                result: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
  /fetchAllCountries:
    post:
      tags:
      - Countries
      summary: AppyWay Fetch All Countries
      description: Returns a list with all the supported countries.
      operationId: post-fetchallcountries
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryIReadOnlyCollectionOkResponse'
              example:
                success: true
                result:
                - id: string
                  name: string
                  specialDays:
                  - id: string
                    name: string
                    isHoliday: true
                    dates:
                    - '2020-01-20'
                  bounds:
                  - - 0
                  defaultBaseMapId: 0
                  entitlementTypes:
                  - 0
                  restrictionTypes:
                  - 0
                  assetTypes:
                  - 0
                  countryCode: string
                  currencyCode: string
                  languageCode: string
                  hasMetricSpeedLimits: true
        '304':
          description: Not Modified
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
  /fetchCountryById:
    post:
      tags:
      - Countries
      summary: AppyWay Fetch Country By Id
      description: Returns a country object if a valid identifier is provided.
      operationId: post-fetchcountrybyid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchCountryByIdQuery'
            example:
              id: string
          text/json:
            schema:
              $ref: '#/components/schemas/FetchCountryByIdQuery'
            example:
              id: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/FetchCountryByIdQuery'
            example:
              id: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryOkResponse'
              example:
                success: true
                result:
                  id: string
                  name: string
                  specialDays:
                  - id: string
                    name: string
                    isHoliday: true
                    dates:
                    - '2020-01-20'
                  bounds:
                  - - 0
                  defaultBaseMapId: 0
                  entitlementTypes:
                  - 0
                  restrictionTypes:
                  - 0
                  assetTypes:
                  - 0
                  countryCode: string
                  currencyCode: string
                  languageCode: string
                  hasMetricSpeedLimits: true
        '304':
          description: Not Modified
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
components:
  schemas:
    ChangeCountrySpecialDaysCommand:
      required:
      - id
      - specialDays
      type: object
      properties:
        id:
          maxLength: 36
          minLength: 1
          type: string
          description: Unique identifier of the country
        specialDays:
          type: array
          items:
            $ref: '#/components/schemas/SpecialDay'
      additionalProperties: false
    CountryOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          $ref: '#/components/schemas/Country'
      additionalProperties: false
    BadRequestResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        message:
          type:
          - string
          - 'null'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Error'
      additionalProperties: false
    StringOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          type:
          - string
          - 'null'
      additionalProperties: false
    Country:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: Unique identifier of the country
        name:
          type:
          - string
          - 'null'
          description: Name of the country
        specialDays:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SpecialDay'
          description: List of holidays and named days that apply to this country.
        bounds:
          type:
          - array
          - 'null'
          items:
            type: array
            items:
              type: number
              format: double
          description: A rectangular area indicating roughly where the country is situated
        defaultBaseMapId:
          type: integer
          description: The default basemap to use for this country
          format: int32
        entitlementTypes:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
          description: Entitlement types available in this country
        restrictionTypes:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
          description: Restriction types available in this country
        assetTypes:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
          description: Asset types available in this country
        countryCode:
          type:
          - string
          - 'null'
          description: ISO 3166-1 alpha-3 country code for this country
        currencyCode:
          type:
          - string
          - 'null'
          description: ISO 4217 currency code for this country
        languageCode:
          type:
          - string
          - 'null'
          description: BCP 47 language tag for this country
        hasMetricSpeedLimits:
          type: boolean
          description: Whether this country uses the metric system for speed limits
      additionalProperties: false
    SpecialDay:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: Unique identifier
        name:
          type:
          - string
          - 'null'
          description: Name
        isHoliday:
          type: boolean
          description: Indicates whether this day is considered a holiday
        dates:
          type:
          - array
          - 'null'
          items:
            type: string
            description: ISO-8601 date pattern
            example: '2020-01-20'
          description: Dates on which this day is in effect
      additionalProperties: false
    CountryIReadOnlyCollectionOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Country'
      additionalProperties: false
    FetchCountryByIdQuery:
      required:
      - id
      type: object
      properties:
        id:
          maxLength: 36
          minLength: 1
          type: string
      additionalProperties: false
    Error:
      type: object
      properties:
        property:
          type:
          - string
          - 'null'
        code:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
      additionalProperties: false
  responses:
    TooManyRequests:
      description: Too many requests
    Forbidden:
      description: Forbidden
    Unauthorized:
      description: Unauthorized
  securitySchemes:
    apiKey:
      name: API-KEY
      in: header
      type: apiKey
    oAuth2:
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://auth.appyway.com/authorize
          tokenUrl: https://auth.appyway.com/oauth/token
      type: oauth2
