openapi: 3.0.1
info:
  title: AppyWay Availability RealTime ActivityTypes Regions API
  version: '1.0'
  description: AppyWay Availability RealTime API allows businesses to access real-time data on parking availability, traffic congestion, and road closure information. This API provides up-to-the-minute updates on parking spots, helping users find and reserve parking spaces quickly and easily. By providing this information in real-time, businesses can improve customer satisfaction and reduce the frustration of searching for parking. Additionally, the API helps businesses optimize their operations by providing detailed information on traffic conditions and road closures, allowing for more efficient route planning and delivery scheduling. Overall, the AppyWay Availability RealTime API is a valuable tool for businesses looking to streamline their operations and improve the customer experience.
servers:
- url: https://api.appyway.com/v1/availability-realtime
security:
- apiKey: []
- oAuth2: []
tags:
- name: Regions
paths:
  /changeRegionVenues:
    post:
      tags:
      - Regions
      summary: AppyWay Change Region Venues
      description: Change Region Venues
      operationId: post-changeregionvenues
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeRegionVenuesCommand'
            example:
              venues:
              - id: string
                name: string
                eventsMustSupplyHours: true
                events:
                - name: string
                  date: '2020-01-20'
                  start: '2024-10-11'
                  end: '2024-10-11'
              id: string
          text/json:
            schema:
              $ref: '#/components/schemas/ChangeRegionVenuesCommand'
            example:
              venues:
              - id: string
                name: string
                eventsMustSupplyHours: true
                events:
                - name: string
                  date: '2020-01-20'
                  start: '2024-10-11'
                  end: '2024-10-11'
              id: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/ChangeRegionVenuesCommand'
            example:
              venues:
              - id: string
                name: string
                eventsMustSupplyHours: true
                events:
                - name: string
                  date: '2020-01-20'
                  start: '2024-10-11'
                  end: '2024-10-11'
              id: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringOkResponse'
              example:
                success: true
                result: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
  /fetchAllRegions:
    post:
      tags:
      - Regions
      summary: AppyWay Fetch All Regions
      description: Returns a list with all the supported country regions.
      operationId: post-fetchallregions
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionIReadOnlyCollectionOkResponse'
              example:
                success: true
                result:
                - id: string
                  countryId: string
                  name: string
                  venues:
                  - id: string
                    name: string
                    eventsMustSupplyHours: true
                    events:
                    - name: string
                      date: '2020-01-20'
                      start: '2024-10-11'
                      end: '2024-10-11'
        '304':
          description: Not Modified
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
  /fetchRegionById:
    post:
      tags:
      - Regions
      summary: AppyWay Fetches a Region By Id
      description: Returns a country region object if a valid identifier is provided.
      operationId: post-fetchregionbyid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchRegionByIdQuery'
            example:
              id: string
          text/json:
            schema:
              $ref: '#/components/schemas/FetchRegionByIdQuery'
            example:
              id: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/FetchRegionByIdQuery'
            example:
              id: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionOkResponse'
              example:
                success: true
                result:
                  id: string
                  countryId: string
                  name: string
                  venues:
                  - id: string
                    name: string
                    eventsMustSupplyHours: true
                    events:
                    - name: string
                      date: '2020-01-20'
                      start: '2024-10-11'
                      end: '2024-10-11'
        '304':
          description: Not Modified
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
components:
  schemas:
    StringOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          type: string
          nullable: true
      additionalProperties: false
    BadRequestResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        message:
          type: string
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          nullable: true
      additionalProperties: false
    Region:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the region
          nullable: true
        countryId:
          type: string
          description: Id of the Country this region belongs to
          nullable: true
        name:
          type: string
          description: Name of the region
          nullable: true
        venues:
          type: array
          items:
            $ref: '#/components/schemas/Venue'
          description: A list of venues that are available in the region. Venues are linked to zones and will affect the operating hours on dates where there's an event at the venue
          nullable: true
      additionalProperties: false
    FetchRegionByIdQuery:
      required:
      - id
      type: object
      properties:
        id:
          maxLength: 36
          minLength: 1
          type: string
      additionalProperties: false
    Event:
      type: object
      properties:
        name:
          type: string
          description: Name of the event
          nullable: true
        date:
          type: string
          description: Date when the event takes place
          example: '2020-01-20'
        start:
          type: string
          description: Start time of the event
          nullable: true
          example: 00:00:00
        end:
          type: string
          description: End time of the event
          nullable: true
          example: 00:00:00
      additionalProperties: false
    RegionIReadOnlyCollectionOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          type: array
          items:
            $ref: '#/components/schemas/Region'
          nullable: true
      additionalProperties: false
    Venue:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the region venue
          nullable: true
        name:
          type: string
          description: Name of the venue
          nullable: true
        eventsMustSupplyHours:
          type: boolean
          description: Indicates whether an event at this venue supplies the hours or whether it should take the hours from the applicable operating hours
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
          description: List of events that will take place at this venue
          nullable: true
      additionalProperties: false
    ChangeRegionVenuesCommand:
      required:
      - id
      - venues
      type: object
      properties:
        id:
          maxLength: 36
          minLength: 1
          type: string
          description: Unique identifier of the region
        venues:
          type: array
          items:
            $ref: '#/components/schemas/Venue'
      additionalProperties: false
    RegionOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          $ref: '#/components/schemas/Region'
      additionalProperties: false
    Error:
      type: object
      properties:
        property:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
  responses:
    TooManyRequests:
      description: Too many requests
    Forbidden:
      description: Forbidden
    Unauthorized:
      description: Unauthorized
  securitySchemes:
    apiKey:
      name: API-KEY
      in: header
      type: apiKey
    oAuth2:
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://auth.appyway.com/authorize
          tokenUrl: https://auth.appyway.com/oauth/token
      type: oauth2
